# Generated by Django 6.1.1 on 2026-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_sha256', models.CharField(max_length=64)),
                ('exit_release', models.CharField(max_length=80)),
                ('geonames_sha256', models.CharField(max_length=64)),
                ('coverage', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelPriceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(unique=True)),
                ('opis_id', models.CharField(blank=True, max_length=32)),
                ('station_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=12)),
                ('rack_id', models.CharField(blank=True, max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('status', models.CharField(max_length=24)),
                ('station_key', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['source_row_number'],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('station_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('opis_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=12)),
                ('price_usd_per_gallon', models.DecimalField(decimal_places=8, max_digits=12)),
                ('price_conflict', models.BooleanField(default=False)),
                ('source_row_numbers', models.JSONField(default=list)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('location_type', models.CharField(db_index=True, max_length=16)),
                ('location_source', models.CharField(blank=True, max_length=32)),
                ('location_reference', models.CharField(blank=True, max_length=128)),
                ('location_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['location_type', 'state'], name='fuel_routes_locatio_521217_idx')],
            },
        ),
    ]
